@extends('layouts.dashboard')

@section('title', 'Horenzo Reports')
@section('page-title', 'Horenzo Reports - Admin')

@section('content')
<div class="row g-4">
    <div class="col-12 col-lg-4">
        <div class="glass-card h-100">
            <h5 class="fw-bold mb-4"><i class="ph ph-funnel text-primary me-2"></i> Generate Report</h5>
            <form action="{{ route('admin.horenzo.generate') }}" method="POST">
                @csrf
                <div class="mb-3">
                    <label class="form-label fw-bold small">Date Range</label>
                    <div class="row g-2">
                        <div class="col-6">
                            <input type="date" name="date_from" class="form-control form-control-sm" value="{{ date('Y-m-01') }}" required>
                        </div>
                        <div class="col-6">
                            <input type="date" name="date_to" class="form-control form-control-sm" value="{{ date('Y-m-d') }}" required>
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label fw-bold small">Shift</label>
                    <select name="shift_id" class="form-select form-select-sm">
                        <option value="">All Shifts</option>
                        @foreach($shifts as $shift)
                            <option value="{{ $shift->id }}">{{ $shift->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label fw-bold small">Process Main</label>
                    <select name="process_main" class="form-select form-select-sm">
                        <option value="">All Processes</option>
                        @foreach($processMains as $pm)
                            <option value="{{ $pm }}">{{ $pm }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label fw-bold small">Part Code</label>
                    <select name="part_code" class="form-select form-select-sm">
                        <option value="">All Parts</option>
                        @foreach($partCodes as $pc)
                            <option value="{{ $pc->code }}">{{ $pc->code }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label fw-bold small">LOT Number</label>
                    <select name="lot_id" class="form-select form-select-sm">
                        <option value="">All LOTs</option>
                        @foreach($lotNumbers as $lot)
                            <option value="{{ $lot->id }}">{{ $lot->code }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-4">
                    <label class="form-label fw-bold small">NIK (keyword)</label>
                    <input type="text" name="nik" class="form-control form-control-sm" placeholder="Cari NIK" value="{{ request('nik') }}">
                </div>
                <button type="submit" class="btn btn-primary w-100 fw-bold">
                    <i class="ph ph-arrows-clockwise me-2"></i> Generate
                </button>
            </form>
        </div>
    </div>

    <div class="col-12 col-lg-8">
        <div class="glass-card">
            <h5 class="fw-bold border-bottom pb-3 mb-3"><i class="ph ph-clock-counter-clockwise text-primary me-2"></i> Generated Reports</h5>
            @if(session('success'))
                <div class="alert alert-success">{{ session('success') }}</div>
            @endif
            <div class="table-responsive">
                <table class="table align-middle">
                    <thead class="table-light">
                        <tr>
                            <th>#</th>
                            <th>Filter</th>
                            <th>Generated By</th>
                            <th>Generated At</th>
                            <th class="text-end">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($reports as $report)
                        <tr>
                            <td>{{ $report->id }}</td>
                            <td>
                                <small>
                                    {{ $report->filter_params['date_from'] ?? '-' }} ~ {{ $report->filter_params['date_to'] ?? '-' }}
                                    @if(!empty($report->filter_params['process_main']))
                                        <br>{{ $report->filter_params['process_main'] }}
                                    @endif
                                </small>
                            </td>
                            <td>{{ $report->generatedBy->name ?? '-' }}</td>
                            <td>{{ $report->created_at->format('d M Y H:i') }}</td>
                            <td class="text-end">
                                <a href="{{ route('admin.horenzo.export', $report->id) }}" class="btn btn-sm btn-outline-primary"><i class="ph ph-download"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="mt-3">{{ $reports->links() }}</div>
        </div>
    </div>
</div>
@endSection